### ISSUE TITLE
what bot u writing? bsc bot?

### ISSUE THREAD

**Issue by cheehau** [ruchern-chong/crypto-helper-bot#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ruchern-chong** [comment]
Nothing special in particular. I was just trying to migrate the code that I had many years ago onto the cloud and that's it. It's a very simple bot actually.

**Comment by cheehau** [comment]
wahhahahaaaha awesome anyway.. @ruchern-chong
